name: Docker (GHCR)

on:
  push:
    branches:
      - release/qa
      - release/testnet
      - release/mainnet
    tags:
      - 'v*.*.*' # release tags

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  qa:
    if: github.ref == 'refs/heads/release/qa'
    uses: ./.github/workflows/_docker-build.yml
    with:
      environment: qa
      image_tag: qa
    secrets: inherit

  testnet:
    if: github.ref == 'refs/heads/release/testnet'
    uses: ./.github/workflows/_docker-build.yml
    with:
      environment: testnet
      image_tag: testnet
    secrets: inherit

  mainnet:
    if: github.ref == 'refs/heads/release/mainnet'
    uses: ./.github/workflows/_docker-build.yml
    with:
      environment: mainnet
      image_tag: mainnet
    secrets: inherit

  release_tag:
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/_docker-build.yml
    with:
      environment: mainnet
      image_tag: mainnet
      release_tag: ${{ github.ref_name }} # e.g., v1.2.3
    secrets: inherit
